### ISSUE TITLE
Documentation for MET data

### ISSUE THREAD

**Issue by gvegayon** [USCbiostats/data-science-data#1]
We need to have the data source + codebook + R script (:stuck_out_tongue:) used to generate the data. I'll add a README.md file that contains some pointers to it. You can drop the R script and point me to the codebook + data source so I can add it to the README.md file.

**Comment by meredithfranklin** [comment]
I added a readme with the variable description and just dropped the script used to dl the data (it might need some work but I tried commenting it well!)

**Comment by gvegayon** [comment]
This is great, I see you added it in 0724504. FYI you can also reference issues in PR and commit messages by just adding [hashtag][issue number], e.g. 

```bash
$ git commit -a -m "Adding desc and script to generate met. Closes #1"
```
Would have been added to this issue and close it, all at once!

**Comment by gvegayon** [comment]
Hey @meredithfranklin, does "met" stands for "Meteorological"?

**Comment by meredithfranklin** [comment]
@gvegayon yes it does!
