### ISSUE TITLE
met data 

### ISSUE THREAD

**Issue by meredithfranklin** [USCbiostats/data-science-data#3]
There is something corrupted in the met data .gz, I can't unpack it. Not sure if it is the csv or the gz. Not working when I download to local or read in directly with data.table.

**Comment by gvegayon** [comment]
Not an issue with the data, it is actually a "problem" with fread. The package tries to download the data using `curl::curl_download` but it times out. Not sure why (or how hard it is to extend the timeout limit) but if you just download the file from here:

https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz

And then read it into R, it works OK. `data.table::fread` actually tries to download the file to a temp file and read it from there, so it is not very different from what you would do. To me it worked.

**Comment by gvegayon** [comment]
OK, so you can actually do the following:

```r
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", timeout = 60)
met <- data.table::fread("met_all.gz")
```

That works.

**Comment by meredithfranklin** [comment]
Looks like that works for me, too. Thanks!
